repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        additional_dependencies: [toml]
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  # Black
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        types: [python]
  # Flake8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, pep8-naming]

  # Mypy
  # run locally to ensure
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        types: [python]
        entry: poetry run mypy open_rarity
        language: system
        always_run: true
        pass_filenames: false
